## Numpy
`NumPy` (short for Numerical Python) is an open-source Python library used for numerical computing and working with arrays, matrices, and mathematical operations efficiently.

In [143]:
import numpy as np

In [144]:
lst = list(range(1,20))
arr = np.array(lst)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [145]:
arr = np.array([1,2,3])             #CREATES ARRAY
arr

array([1, 2, 3])

In [146]:
arr = np.array([range(1,29)])
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28]])

In [147]:
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [148]:
arr.ndim

2

In [149]:
arr =np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [150]:
arr = np.linspace(1,10,5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [151]:
arr = np.arange(1,10)                 #inbuilt function to create array from a range
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [152]:
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [153]:
arr = np.random.randint(1,5,(5,6))
arr

array([[3, 3, 3, 4, 2, 1],
       [3, 3, 3, 2, 1, 3],
       [3, 2, 3, 4, 2, 1],
       [4, 3, 4, 1, 3, 1],
       [2, 3, 2, 2, 4, 3]], dtype=int32)

In [154]:
arr = np.random.random((5,2))
arr

array([[0.6919298 , 0.32255081],
       [0.53934194, 0.55343346],
       [0.91422112, 0.32790421],
       [0.79705541, 0.71275632],
       [0.02527505, 0.00253645]])

In [155]:
arr  = np.arange(60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [156]:
print(arr.ndim)
print(arr.shape)
print(arr.dtype)
print(arr.size)

2
(12, 5)
int64
60


In [157]:
lst = [[1,2,3],[2,3,4]]
lst

[[1, 2, 3], [2, 3, 4]]

In [158]:
arr = np.array(lst)
arr

array([[1, 2, 3],
       [2, 3, 4]])

In [159]:
arr = np.arange(60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [160]:
print(arr.ndim)
print(arr.shape)
print(arr.dtype)
print(arr.size)

2
(12, 5)
int64
60


In [161]:
arr[2:4]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [162]:
arr[5:7,2:4]

array([[27, 28],
       [32, 33]])

In [163]:
arr[0:9,3:4]

array([[ 3],
       [ 8],
       [13],
       [18],
       [23],
       [28],
       [33],
       [38],
       [43]])

### 3D Array 

In [164]:
arr = np.arange(225).reshape(5,15,3)
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

### Indexing of 3D Array

In [165]:
arr[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [166]:
arr[0,0,0]          

np.int64(0)

In [167]:
arr[0,4,2]

np.int64(14)

### Slicing of 3D Array

In [168]:
arr[0:5,0:1]

array([[[  0,   1,   2]],

       [[ 45,  46,  47]],

       [[ 90,  91,  92]],

       [[135, 136, 137]],

       [[180, 181, 182]]])

In [169]:
arr[0:5,0:1,0:1]

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [170]:
arr[0:5,2:4]

array([[[  6,   7,   8],
        [  9,  10,  11]],

       [[ 51,  52,  53],
        [ 54,  55,  56]],

       [[ 96,  97,  98],
        [ 99, 100, 101]],

       [[141, 142, 143],
        [144, 145, 146]],

       [[186, 187, 188],
        [189, 190, 191]]])

In [171]:
arr[0:5,:,2:3]

array([[[  2],
        [  5],
        [  8],
        [ 11],
        [ 14],
        [ 17],
        [ 20],
        [ 23],
        [ 26],
        [ 29],
        [ 32],
        [ 35],
        [ 38],
        [ 41],
        [ 44]],

       [[ 47],
        [ 50],
        [ 53],
        [ 56],
        [ 59],
        [ 62],
        [ 65],
        [ 68],
        [ 71],
        [ 74],
        [ 77],
        [ 80],
        [ 83],
        [ 86],
        [ 89]],

       [[ 92],
        [ 95],
        [ 98],
        [101],
        [104],
        [107],
        [110],
        [113],
        [116],
        [119],
        [122],
        [125],
        [128],
        [131],
        [134]],

       [[137],
        [140],
        [143],
        [146],
        [149],
        [152],
        [155],
        [158],
        [161],
        [164],
        [167],
        [170],
        [173],
        [176],
        [179]],

       [[182],
        [185],
        [188],
        [191],
        [194],
        [197],
  

In [172]:
arr[0:5,0:15,1:2]

array([[[  1],
        [  4],
        [  7],
        [ 10],
        [ 13],
        [ 16],
        [ 19],
        [ 22],
        [ 25],
        [ 28],
        [ 31],
        [ 34],
        [ 37],
        [ 40],
        [ 43]],

       [[ 46],
        [ 49],
        [ 52],
        [ 55],
        [ 58],
        [ 61],
        [ 64],
        [ 67],
        [ 70],
        [ 73],
        [ 76],
        [ 79],
        [ 82],
        [ 85],
        [ 88]],

       [[ 91],
        [ 94],
        [ 97],
        [100],
        [103],
        [106],
        [109],
        [112],
        [115],
        [118],
        [121],
        [124],
        [127],
        [130],
        [133]],

       [[136],
        [139],
        [142],
        [145],
        [148],
        [151],
        [154],
        [157],
        [160],
        [163],
        [166],
        [169],
        [172],
        [175],
        [178]],

       [[181],
        [184],
        [187],
        [190],
        [193],
        [196],
  

In [173]:
arr[0:5,14:,2:]

array([[[ 44]],

       [[ 89]],

       [[134]],

       [[179]],

       [[224]]])

In [174]:
arr[0:5,-1:,-1:]

array([[[ 44]],

       [[ 89]],

       [[134]],

       [[179]],

       [[224]]])

In [175]:
arr[-1,-1,-1]

np.int64(224)

In [176]:
print(arr.ndim)
print(arr.shape)
print(arr.dtype)
print(arr.size)

3
(5, 15, 3)
int64
225


In [177]:
arr[-1,-1,-1] = 226

In [178]:
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

### Operations on Array

In [179]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([2, 4, 6, 8])

print("Array 1 :", arr1)
print("Array 2 :", arr2)

print("\n========== OPERATIONS ==========\n")

# Multiplication
print("1️⃣ Multiplication (*)")
print("arr1 * arr2 =", arr1 * arr2)

# Division
print("\n2️⃣ Division (/)")
print("arr1 / arr2 =", arr1 / arr2)

# Addition
print("\n3️⃣ Addition (+)")
print("arr1 + arr2 =", arr1 + arr2)

# Subtraction
print("\n4️⃣ Subtraction (-)")
print("arr1 - arr2 =", arr1 - arr2)

# Positive Sign with Multiplication
print("\n5️⃣ Multiplication with Unary Plus (* +)")
print("arr1 * +arr2 =", arr1 * +arr2)

# Floor Division
print("\n6️⃣ Floor Division (//)")
print("arr1 // +arr2 =", arr1 // +arr2)

print("\n✅ All operations completed successfully!")

Array 1 : [10 20 30 40]
Array 2 : [2 4 6 8]

========== OPERATIONS ==========

1️⃣ Multiplication (*)
arr1 * arr2 = [ 20  80 180 320]

2️⃣ Division (/)
arr1 / arr2 = [5. 5. 5. 5.]

3️⃣ Addition (+)
arr1 + arr2 = [12 24 36 48]

4️⃣ Subtraction (-)
arr1 - arr2 = [ 8 16 24 32]

5️⃣ Multiplication with Unary Plus (* +)
arr1 * +arr2 = [ 20  80 180 320]

6️⃣ Floor Division (//)
arr1 // +arr2 = [5 5 5 5]

✅ All operations completed successfully!


In [180]:
arr1 = np.array([2,3231,334525,32])
print(arr1.sort())

None


In [181]:
arr1

array([     2,     32,   3231, 334525])

In [182]:
arr1d = np.array([1,2,3,4,3,4,5,3])
arr1d

array([1, 2, 3, 4, 3, 4, 5, 3])

In [183]:
arr1d.reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[3, 4],
        [5, 3]]])